services:      # 컨테이너들 정의
  nginx:       # 컨테이너(service) 이름
    build: ./nginx    # 이 폴더의 Dockerfile로 build
    ports: # 외부에 포트 열어줌
      - "80:80"       # 포트 연결
    restart: always
  
  fastapi:     
    build: ./fastapi  
    expose: # 내부에서만 통신 (외부 노출 안 됨)
      - "8000"
    restart: always
    depends_on: # 실행 순서
      - db # db 먼저 띄우고 fastapi 실행

  db:
    image: postgres # image를 커스터마이징할 필요가 없으므로 image 사용
    expose: 
      - "5432"
    environment:
      # .env에서 가져오기
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
