services:      # 컨테이너들 정의
  nginx:       # 컨테이너 이름
    build: ./nginx    # 이 폴더의 Dockerfile로 build
    ports:
      - "80:80"       # 포트 연결
  
  fastapi:     
    build: ./fastapi  
    ports:
      - "8000:8000"