server {           # 서버 설정 시작
  listen 80;     # 80포트로 들어오는 요청 받겠다

  location / {   # "/" 경로로 들어오면 (모든 요청)
    # container끼리 같은 네트워크이며 서비스 이름으로 통신 가능
    proxy_pass http://fastapi:8000;  # fastapi 컨테이너 8000으로 넘겨줘
  }
}